
import time


support_models = ['./models/Llama-3.1-8B-Instruct',
                  "/home/rdaha1@AD/bias/Multi-Agents-Debate/models/medgemma-27b-text-it",
                  "/home/rdaha1@AD/bias/Multi-Agents-Debate/models/Llama-3.3-70B-Instruct"]

class Members:
    def __init__(self, model_name: str, name: str, temperature: float, sleep_time: float=0) -> None:
        """Create an agent

        Args:
            model_name(str): model name
            name (str): name of this agent
            temperature (float): higher values make the output more random, while lower values make it more focused and deterministic
            sleep_time (float): sleep because of rate limits
        """
        self.model_name = model_name
        self.name = name
        self.temperature = temperature
        self.memory_lst = []
        self.sleep_time = sleep_time

    def query(self,tokenizer,model, messages: "list[dict]", max_tokens: int, temperature: float) -> str:
        """make a query

        Args:
            messages (list[dict]): chat history in turbo format
            max_tokens (int): max token in api call
            temperature (float): sampling temperature

        Raises:
            OutOfQuotaException: the apikey has out of quota
            AccessTerminatedException: the apikey has been ban

        Returns:
            str: the return msg
        """
        time.sleep(self.sleep_time)
        assert self.model_name in support_models, f"Not support {self.model_name}. Choices: {support_models}"
        input_text = " ".join([message["content"] for message in messages])
        inputs = tokenizer(input_text, return_tensors="pt") 
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        input_length = inputs["input_ids"].shape[1]  
        output_tokens = model.generate(
            **inputs,
            do_sample=True,  
            temperature=0.5, 
            return_dict_in_generate=True,
            max_new_tokens=250,
            output_scores=True
        )
        new_tokens = output_tokens.sequences[:, input_length:]
        response = tokenizer.decode(new_tokens[0], skip_special_tokens=True)
    # )
        return response


    def set_meta_prompt(self, meta_prompt: str):
        """Set the meta_prompt

        Args:
            meta_prompt (str): the meta prompt
        """
        self.memory_lst.append({"role": "system", "content": f"{meta_prompt}"})

    def add_event(self, event: str):
        """Add an new event in the memory

        Args:
            event (str): string that describe the event.
        """
        self.memory_lst.append({"role": "user", "content": f"{event}"})

    def add_memory(self, memory: str):
        """Monologue in the memory

        Args:
            memory (str): string that generated by the model in the last round.
        """
        self.memory_lst.append({"role": "assistant", "content": f"{memory}"})
        print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, tokenizer,model,temperature: float=None):
        """Query for answer

        Args:
        """
        max_token=4000 
        return self.query(tokenizer,model,self.memory_lst, max_token, temperature=temperature if temperature else self.temperature)  #I am here

